import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const WordGameApp());
}

class WordGameApp extends StatelessWidget {
  const WordGameApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: WordGameScreen(),
    );
  }
}

class WordGameScreen extends StatefulWidget {
  const WordGameScreen({super.key});

  @override
  State<WordGameScreen> createState() => _WordGameScreenState();
}

class _WordGameScreenState extends State<WordGameScreen> {
  final TextEditingController _controller = TextEditingController();
  String hint = "";
  String feedback = "";
  String correctAnswer = "";
  String guess = "";
  int attempts = 0;
  final int maxAttempts = 3;
  final random = Random();

  final Map<String, List<String>> categories = {
    "BIRD": [
      "PEACOCK",
      "SPARROW",
      "PIGEON",
      "CROW",
      "PARROT",
      "EAGLE",
      "OWL",
      "DUCK",
      "KINGFISHER",
      "FLAMINGO",
      "MYNA",
      "KOEL",
      "DOVE",
      "KITE",
      "BLACK DRONGO",
      "INDIAN ROBIN",
      "WHITE-BREASTED KINGFISHER",
      "JUNGLE BABBLER",
      "BRAHMINY KITE",
      "INDIAN ROLLER",
      "HOOPOE",
      "GREY FRANCOLIN",
      "COMMON MYNA",
      "ORIENTAL MAGPIE ROBIN",
      "ROSE-RINGED PARAKEET",
      "PURPLE SUNBIRD",
      "BULBUL",
      "ASIAN KOEL",
      "HOUSE CROW",
      "CATTLE EGRET",
      "PIED BUSHCHAT",
      "INDIAN POND HERON",
      "GREEN BEE-EATER",
      "INDIAN SILVERBILL",
      "RED-VENTED BULBUL",
      "INDIAN ORIOLE",
      "COMMON IORA",
      "GREAT EGRET",
      "BLACK KITE",
      "SPOTTED OWLET",
      "RED-WATTLED LAPWING",
      "INDIAN PEAHEN",
      "PIED KINGFISHER",
      "GREEN PIGEON",
      "RUFOUS TREEPIE",
      "INDIAN GREY HORNBILL",
      "WHITE-THROATED KINGFISHER",
      "ASHY PRINIA",
      "SPOTTED DOVE",
      "INDIAN BUSH LARK",
    ],
    "ANIMAL": [
      "DOG",
      "CAT",
      "COW",
      "HORSE",
      "CHICKEN",
      "SHEEP",
      "GOAT",
      "PIG",
      "LION",
      "TIGER",
      "ELEPHANT",
      "MONKEY",
      "BEAR",
      "DEER",
      "SNAKE",
      "RABBIT",
      "SQUIRREL",
      "FISH",
      "DOLPHIN",
      "WHALE",
      "SHARK",
      "CROCODILE",
      "ALLIGATOR",
      "ZEBRA",
      "GIRAFFE",
      "CHEETAH",
      "LEOPARD",
      "FOX",
      "WOLF",
      "KANGAROO",
      "PANDA",
      "KOALA",
      "RHINOCEROS",
      "HIPPOPOTAMUS",
      "BAT",
      "PEACOCK",
      "PARROT",
      "PIGEON",
      "BUTTERFLY",
      "SPARROW",
      "OWL",
      "EAGLE",
      "HAWK",
      "FALCON",
      "TURTLE",
      "FROG",
      "TOAD",
      "IGUANA",
      "LIZARD",
      "CATERPILLAR",
      "SPIDER",
      "SCORPION",
      "ANT",
      "BEE",
      "MOSQUITO",
      "FLY",
      "CRAB",
      "LOBSTER",
      "OCTOPUS",
      "JELLYFISH",
      "STARFISH",
      "CHIMPANZEE",
      "GORILLA",
      "OTTER",
      "RACCOON",
      "SKUNK",
      "HYENA",
      "ORANGUTAN",
      "MOOSE",
      "BISON",
      "BUFFALO",
      "CAMEL",
      "WALRUS",
      "SEAL",
      "FERRET",
      "MEERKAT",
      "HEDGEHOG",
      "BADGER",
      "LYNX",
      "BOBCAT",
      "WOLVERINE",
      "HONEY BADGER",
      "MANATEE",
      "DINGO",
      "ANTELLOPE",
      "GAZELLE",
      "IBEX",
      "MULE",
      "PECCARY",
      "LEMUR",
      "KUDU",
      "ELAND",
      "OKAPI",
      "PORCUPINE",
      "CARIBOU",
      "PRAIRIE DOG",
      "ARMADILLO",
      "PANGOLIN",
      "TAPIR",
      "VICUNA",
      "SPRINGBOK",
      "SLOTH",
      "CHINCHILLA",
      "BONGO",
      "AGOUTI",
    ],
    "FLOWER": [
      "ROSE",
      "TULIP",
      "LILY",
      "DAFFODIL",
      "ORCHID",
      "JASMINE",
      "SUNFLOWER",
      "DAISY",
      "MARIGOLD",
      "CARNATION",
      "LOTUS",
      "CHERRY BLOSSOM",
      "LAVENDER",
      "VIOLET",
      "HIBISCUS",
      "CROCUS",
      "PEONY",
      "CAMILIA",
      "GERANIUM",
      "AZALEA",
      "IRIS",
      "CAMPANULA",
      "FREESIA",
      "HEDGES",
      "PLUMERIA",
      "GERBERA",
      "PANSY",
      "ZINNIA",
      "PETUNIA",
      "BEGONIA",
      "IMPATIENS",
      "SNAPDRAGON",
      "HELLEBORE",
      "AMARYLLIS",
      "GARDENIA",
      "HOLLYHOCK",
      "NARCISSUS",
      "ALSTROEMERIA",
      "SCABIOSA",
      "STOCK",
      "YARROW",
      "TIGER LILY",
      "MARANTA",
      "WISTERIA",
      "FUCHSIA",
      "BLOODROOT",
      "CHRISTMAS CACTUS",
      "POTTED PRIMROSE",
      "CALLA LILY",
      "COLUMBINE",
      "ASTER",
      "MORNING GLORY",
      "PETALONIA",
    ],
    "CITY": [
      "MUMBAI",
      "DELHI",
      "KOLKATA",
      "BENGALURU",
      "CHENNAI",
      "HYDERABAD",
      "PUNE",
      "AHMEDABAD",
      "Kochi",
      "LUCKNOW",
      "JAIPUR",
      "SURAT",
      "PATNA",
      "INDORE",
      "CHANDIGARH",
      "BHOPAL",
      "VADODARA",
      "VISAKHAPATNAM",
      "GOA",
      "RANCHI",
      "MYSURU",
      "THANE",
      "KANPUR",
      "AGRA",
      "VARANASI",
      "NAGPUR",
      "BHUJ",
      "SHIMLA",
      "DEHRA DUN",
      "GURUGRAM",
      "NOIDA",
      "FARIDABAD",
      "IMPHAL",
      "DISPUR",
      "PORT BLAIR",
      "GAYA",
      "JAMMU",
      "LEH",
      "MANALI",
      "SRINAGAR",
      "JAISALMER",
      "JODHPUR",
      "BIKANER",
      "UDAIPUR",
      "RISHIKESH",
      "BARNALA",
      "LUDHIANA",
      "RAIPUR",
      "KHARAGPUR",
      "MIRZAPUR",
      "JABALPUR",
      "TIRUNELVELI",
      "NASHIK",
      "BELAGAVI",
      "SHIRDI",
    ],
    "GADGET": [
      "SMARTPHONE",
      "LAPTOP",
      "TABLET",
      "SMARTWATCH",
      "WIRELESS EARPHONES",
      "EARBUDS",
      "POWER BANK",
      "FITNESS TRACKER",
      "DIGITAL CAMERA",
      "DRONE",
      "SMART TV",
      "MICROWAVE OVEN",
      "AIR PURIFIER",
      "KITCHEN BLENDER",
      "GAMING CONSOLE",
      "PRINTER",
      "HEADPHONES",
      "SMART SPEAKER",
      "E-READER",
      "GAMING MOUSE",
      "GAMING KEYBOARD",
      "VIRTUAL REALITY HEADSET",
      "ELECTRIC TOOTHBRUSH",
      "ROBOT VACUUM",
      "SMART LIGHTBULB",
      "BLUETOOTH SPEAKER",
      "SMART PLUG",
      "MICROPHONE",
      "PROJECTOR",
      "EXTERNAL HARD DRIVE",
      "USB FLASH DRIVE",
      "ACTION CAMERA",
      "WIFI ROUTER",
      "RICE COOKER",
      "SLOW COOKER",
      "COFFEE MACHINE",
      "HAIR DRYER",
      "SMART THERMOSTAT",
      "SMART LOCK",
      "DRY IRON",
      "STEAM IRON",
      "RECHARGEABLE FAN",
      "COOLING PAD",
      "DESK LAMP",
      "VIDEO DOORBELL",
      "LAPTOP COOLER",
      "ROBOTIC TOY",
      "CAMERA GIMBAL",
      "BLUETOOTH RECEIVER",
      "SOLAR POWER BANK",
      "INDOOR GARDEN KIT",
      "FOOD DEHYDRATOR",
      "WIRELESS CHARGER",
      "ACTION CAMERA",
      "SMARTGLASSES",
      "PORTABLE AIR CONDITIONER",
      "SECURITY CAMERA",
      "GUITAR TUNER",
    ],
    "BODY ORGAN": [
      "HEART",
      "BRAIN",
      "LIVER",
      "KIDNEY",
      "LUNGS",
      "STOMACH",
      "INTESTINE",
      "BLADDER",
      "SKIN",
      "SPLEEN",
      "PANCREAS",
      "EYES",
      "EARS",
      "NOSE",
      "MOUTH",
      "TEETH",
      "TONGUE",
      "BONES",
      "MUSCLES",
      "BLOOD VESSELS",
      "NERVES",
      "THYMUS",
      "ADRENAL GLANDS",
      "THYROID",
      "PARATHYROID GLANDS",
      "PITUITARY GLAND",
      "PINEAL GLAND",
      "PROSTATE",
      "OVARIES",
      "TESTES",
      "LARYNX",
      "PHARYNX",
      "TRACHEA",
      "ESOPHAGUS",
      "COLON",
      "RECTUM",
      "ANUS",
      "LARGE INTESTINE",
      "SMALL INTESTINE",
      "APPENDIX",
      "CEREBELLUM",
      "CEREBRUM",
      "CORNEA",
      "RETINA",
      "OPTIC NERVE",
      "CORONARY ARTERIES",
      "LYMPH NODES",
      "LYMPHATIC VESSELS",
      "VAGINA",
      "CERVIX",
      "URETHRA",
    ],
    "CAR": [
      "TOYOTA COROLLA",
      "HONDA CIVIC",
      "HYUNDAI SANTRO",
      "MARUTI SUZUKI SWIFT",
      "TATA NEXON",
      "HONDA CITY",
      "TOYOTA CAMRY",
      "MARUTI SUZUKI BALENO",
      "FORD FIESTA",
      "RENAULT KWID",
      "NISSAN MICRA",
      "MAHINDRA XUV500",
      "HYUNDAI CRETA",
      "TOYOTA INNOVA",
      "MARUTI SUZUKI DZIRE",
      "HYUNDAI I20",
      "TOYOTA FORTUNER",
      "MAHINDRA THAR",
      "MARUTI SUZUKI ALTO",
      "KIA Seltos",
      "TATA TIAGO",
      "HONDA JAZZ",
      "FORD ECOSPORT",
      "SKODA RAPID",
      "VOLKSWAGEN POLO",
      "TATA HARIER",
      "RENAULT DUSTER",
      "SUZUKI VITARA",
      "HYUNDAI VENUE",
      "HONDA WR-V",
      "MARUTI SUZUKI CELERIO",
      "MITSUBISHI OUTLANDER",
      "CHEVROLET SPARK",
      "FIAT PUNTO",
      "NISSAN SUNNY",
      "TOYOTA YARIS",
      "HYUNDAI TUCSON",
      "KIA SONET",
      "MARUTI SUZUKI ERTIGA",
      "TATA ALTROZ",
      "MAHINDRA SCORPIO",
      "NISSAN TERRANO",
      "HONDA ACCORD",
      "BMW 3 SERIES",
      "MERCEDES-BENZ E-CLASS",
      "AUDI A4",
      "SKODA OCTAVIA",
      "TOYOTA LAND CRUISER",
      "SUZUKI WAGON R",
      "VOLKSWAGEN TIGUAN",
      "HONDA CR-V",
      "HYUNDAI I10",
    ],
    "WORD": [
      "WAKE UP",
      "BRUSH",
      "SHOWER",
      "BREAKFAST",
      "LUNCH",
      "DINNER",
      "WORK",
      "STUDY",
      "READ",
      "WRITE",
      "EXERCISE",
      "RELAX",
      "MEETING",
      "CALL",
      "TEXT",
      "WALK",
      "CLEAN",
      "COOK",
      "SHOP",
      "LAUNDRY",
      "TIDY",
      "SLEEP",
      "WAKE",
      "WATCH TV",
      "WATCH MOVIE",
      "LISTEN",
      "EAT",
      "DRINK",
      "CHAT",
      "GREET",
      "HUG",
      "SMILE",
      "LAUGH",
      "SING",
      "DANCE",
      "JOG",
      "GARDEN",
      "TIDY UP",
      "ORGANIZE",
      "VISIT",
      "HELP",
      "PLAN",
      "MEDITATE",
      "RELAX",
      "STRETCH",
      "GIVE",
      "RECEIVE",
      "THANK",
      "APOLOGIZE",
      "MEET",
      "LEAVE",
      "ARRIVE",
      "CLOSE",
      "OPEN",
      "DECIDE",
      "CHOOSE",
      "SCHEDULE",
      "SHOPPING",
      "BUY",
      "SELL",
      "PAY",
      "RECEIVE",
      "WORKOUT",
      "REST",
      "TALK",
      "SIT",
      "STAND",
      "WAIT",
      "ANSWER",
      "ASK",
      "FOLLOW",
      "LEARN",
      "REMIND",
      "FORGET",
      "ACCEPT",
      "REFUSE",
      "GO",
    ],
  };

  void startNewGame() {
    setState(() {
      attempts = 0;
      feedback = "";
      _controller.clear();
      final category = categories.entries.elementAt(
        random.nextInt(categories.length),
      );
      correctAnswer =
          category.value[random.nextInt(category.value.length)].toUpperCase();
      hint =
          "THIS IS THE NAME OF ${category.key} WHICH CONTAINS ${correctAnswer.length} LETTERS";
    });
  }

  Widget buildColoredGuess(String guess, String correct) {
    List<TextSpan> spans = [];
    for (int i = 0; i < guess.length; i++) {
      Color color = correct.contains(guess[i]) ? Colors.green : Colors.red;
      spans.add(
        TextSpan(
          text: guess[i],
          style: TextStyle(
            color: color,
            fontSize: 28,
            fontWeight: FontWeight.bold,
          ),
        ),
      );
    }
    return RichText(
      textAlign: TextAlign.center,
      text: TextSpan(children: spans),
    );
  }

  void checkGuess() {
    setState(() {
      guess = _controller.text.trim().toUpperCase();
      if (guess == correctAnswer) {
        feedback = "YEE HOO YOU GIVE RIGHT ANSWER 😎 ✌ ✌";
      } else {
        attempts++;
        if (attempts >= maxAttempts) {
          feedback = "RIGHT ANSWER 😊 😎: $correctAnswer";
        } else {
          feedback =
              "OOPS! YOUR ANSWER IS WRONG. NOW YOU HAVE ONLY ${maxAttempts - attempts} ATTEMPTS LEFT 🤡 🤡";
        }
      }
    });
  }

  @override
  void initState() {
    super.initState();
    startNewGame();
  }

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    final isSmall = size.width < 600;

    return Scaffold(
      backgroundColor: Colors.blueGrey[900],
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: ConstrainedBox(
            constraints: BoxConstraints(maxWidth: 700),
            child: Column(
              children: [
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.black.withOpacity(0.7),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    hint,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: isSmall ? 18 : 22,
                      fontWeight: FontWeight.bold,
                    ),
                    textAlign: TextAlign.center,
                  ),
                ),
                const SizedBox(height: 30),
                TextField(
                  controller: _controller,
                  style: TextStyle(color: Colors.white, fontSize: 26),
                  decoration: InputDecoration(
                    filled: true,
                    fillColor: Colors.black.withOpacity(0.7),
                    hintText: "Enter your guess",
                    hintStyle: const TextStyle(color: Colors.white54),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
                const SizedBox(height: 20),
                ElevatedButton(
                  onPressed: checkGuess,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.amber[600],
                    minimumSize: Size(double.infinity, 50),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: const Text("SUBMIT", style: TextStyle(fontSize: 22)),
                ),
                const SizedBox(height: 30),
                Container(
                  height: 60,
                  alignment: Alignment.center,
                  decoration: BoxDecoration(
                    color: Colors.black.withOpacity(0.6),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child:
                      guess.isEmpty || guess == correctAnswer
                          ? Text(
                            feedback,
                            style: TextStyle(
                              fontSize: 20,
                              color:
                                  guess == correctAnswer
                                      ? Colors.green
                                      : Colors.amber,
                            ),
                          )
                          : buildColoredGuess(guess, correctAnswer),
                ),
                const SizedBox(height: 30),
                Container(
                  width: double.infinity,
                  height: 60,
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: const Color(0xFFddd0c8),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Center(
                    child: Text(
                      feedback,
                      style: const TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ),
                ),
                const SizedBox(height: 30),
                ElevatedButton(
                  onPressed: startNewGame,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.black,
                    foregroundColor: Colors.white,
                    minimumSize: Size(double.infinity, 50),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: const Text("SWITCH", style: TextStyle(fontSize: 22)),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

